### PR TITLE
Use <script> instead of hidden <div>'s

### PR DESCRIPTION
**Pull request by teameh**
The react-on-rails npm package expects `<scripts>`'s now instead of hidden `<div>`'s.

### CODE REVIEW

**Comment by teameh** [comment]
I think it makes sense to bump the major version for this, but unfortunately, react-on-rails did not... (see https://github.com/shakacode/react_on_rails/issues/796).

If they don't decide to bump their major version, then I think this needs some explanation in the docs of ReactRenderer and ReactBundle

**Comment by tiemevanveen** [comment]
Not sure why Travis is failing..

**Comment by nacmartin** [comment]
Sure, thanks. I was aware of this, https://github.com/Limenius/symfony-react-sandbox/issues/25 In fact I wanted to update this library during the weekend.

I was unaware about they not bumping the version of the package, so, yes, it is good to have an explanation in the README. Thanks!

**Comment by nacmartin** [comment]
Thanks a lot! 👍 It is tagged as 0.12.0, I guess that we could make this v.1.0 soon.

**Comment by nacmartin** [comment]
About the testing, it is because of Phpunit6, I have updated this to Phpunit6, don't worry about it.

**Comment by teameh** [comment]
Great! Thanks for your quick response time!

**Pull request merged**
